engines:
  structure:
    enabled: true
    channel: java
  duplication:
    enabled: true
    channel: java
    config:
      languages:
        - java
ratings:
  paths:
    - "**.java"
exclude_paths:
  - "**.js"
  - "**.jsx"
  - "**.rb"
  - "**.py"
